
export const GLOBAL_BLOGS_LIST_REQUEST = "GLOBAL_BLOGS_LIST_REQUEST";
export const GLOBAL_BLOGS_LIST_SUCCESS = "GLOBAL_BLOGS_LIST_SUCCESS";
export const GLOBAL_BLOGS_LIST_FAIL = "GLOBAL_BLOGS_LIST_FAIL";